
//! Autogenerated weights for `staking_pool`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-22, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/gafi-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// staking_pool
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --json-file=raw.json
// --output
// ./pallets/benchmarks/staking_pool/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn set_max_player(s: u32, ) -> Weight;
}

/// Weight functions for `staking_pool`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
		// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: StakingPool MaxPlayer (r:0 w:1)
	fn set_max_player(_s: u32, ) -> Weight {
		(10_000_000_u64)
			.saturating_add(T::DbWeight::get().reads(4_u64 ))
			.saturating_add(T::DbWeight::get().writes(3_u64 ))
	}
}


impl WeightInfo for () {
	fn set_max_player(_s: u32, ) -> Weight {
		(10_000_000_u64)
			.saturating_add(RocksDbWeight::get().reads(4_u64 ))
			.saturating_add(RocksDbWeight::get().writes(3_u64 ))
	}
}
