
//! Autogenerated weights for pallet_game
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-07-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `admin`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

//SBP-M2: I would suggest to use https://github.com/paritytech/substrate/blob/master/.maintain/frame-weight-template.hbs
// Executed Command:
// ./target/release/gafi-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution
// compiled
// --pallet
// pallet_game
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --execution
// wasm
// --output
// ./benchmarking/pallet-game/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_game.
pub trait WeightInfo {
	fn create_game(s: u32, ) -> Weight;
	fn create_game_collection(s: u32, ) -> Weight;
	fn create_item(s: u32, ) -> Weight;
	fn add_supply(s: u32, ) -> Weight;
	fn burn(s: u32, ) -> Weight;
	fn transfer(s: u32, ) -> Weight;
	fn set_upgrade_item(s: u32, ) -> Weight;
	fn upgrade_item(s: u32, ) -> Weight;
	fn set_price(s: u32, ) -> Weight;
	fn buy_item(s: u32, ) -> Weight;
	fn set_bundle(s: u32, ) -> Weight;
	fn buy_bundle(s: u32, ) -> Weight;
	fn set_wishlist(s: u32, ) -> Weight;
	fn claim_wishlist(s: u32, ) -> Weight;
	fn remove_collection(s: u32, ) -> Weight;
	fn set_swap(s: u32, ) -> Weight;
	fn claim_swap(s: u32, ) -> Weight;
	fn set_auction(s: u32, ) -> Weight;
	fn bid_auction(s: u32, ) -> Weight;
	fn claim_auction(s: u32, ) -> Weight;
	fn set_buy(s: u32, ) -> Weight;
	fn claim_set_buy(s: u32, ) -> Weight;
	fn create_collection(s: u32, ) -> Weight;
	fn set_accept_adding(s: u32, ) -> Weight;
	fn add_game_collection(s: u32, ) -> Weight;
	fn add_retail_supply(s: u32, ) -> Weight;
	fn cancel_trade(s: u32, ) -> Weight;
	fn create_dynamic_pool(s: u32, ) -> Weight;
	fn create_stable_pool(s: u32, ) -> Weight;
	fn mint(s: u32, ) -> Weight;
}

/// Weights for pallet_game using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Game NextGameId (r:1 w:1)
	/// Proof: Game NextGameId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game GameAccount (r:0 w:1)
	/// Proof: Game GameAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Game Game (r:0 w:1)
	/// Proof: Game Game (max_values: None, max_size: Some(96), added: 2571, mode: MaxEncodedLen)
	/// Storage: Game GameRoleOf (r:0 w:1)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_game(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3593`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(37_361_427, 3593)
			// Standard Error: 7_566
			.saturating_add(Weight::from_parts(10_746, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Game GameRoleOf (r:1 w:0)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game Game (r:1 w:0)
	/// Proof: Game Game (max_values: None, max_size: Some(96), added: 2571, mode: MaxEncodedLen)
	/// Storage: Nfts NextCollectionId (r:1 w:1)
	/// Proof: Nfts NextCollectionId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game CollectionsOf (r:1 w:1)
	/// Proof: Game CollectionsOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Game GamesOf (r:1 w:1)
	/// Proof: Game GamesOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:0 w:1)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:0 w:1)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionAccount (r:0 w:1)
	/// Proof: Nfts CollectionAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_game_collection(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `388`
		//  Estimated: `3593`
		// Minimum execution time: 59_000_000 picoseconds.
		Weight::from_parts(61_561_967, 3593)
			// Standard Error: 7_486
			.saturating_add(Weight::from_parts(14_608, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts Item (r:1 w:1)
	/// Proof: Nfts Item (max_values: None, max_size: Some(491), added: 2966, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:1)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game SupplyOf (r:0 w:1)
	/// Proof: Game SupplyOf (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
	/// Storage: Nfts Account (r:0 w:1)
	/// Proof: Nfts Account (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_item(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `3956`
		// Minimum execution time: 72_000_000 picoseconds.
		Weight::from_parts(74_392_577, 3956)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game SupplyOf (r:1 w:1)
	/// Proof: Game SupplyOf (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn add_supply(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `513`
		//  Estimated: `3549`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_340_427, 3549)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn burn(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3549`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_358_161, 3549)
			// Standard Error: 7_583
			.saturating_add(Weight::from_parts(13_681, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn transfer(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3549`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_023_896, 3549)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:2 w:1)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemMetadataOf (r:1 w:1)
	/// Proof: Nfts ItemMetadataOf (max_values: None, max_size: Some(140), added: 2615, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game UpgradeConfigOf (r:1 w:1)
	/// Proof: Game UpgradeConfigOf (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// Storage: Nfts Item (r:1 w:1)
	/// Proof: Nfts Item (max_values: None, max_size: Some(491), added: 2966, mode: MaxEncodedLen)
	/// Storage: Game OriginItemOf (r:0 w:1)
	/// Proof: Game OriginItemOf (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Game LevelOf (r:0 w:1)
	/// Proof: Game LevelOf (max_values: None, max_size: Some(44), added: 2519, mode: MaxEncodedLen)
	/// Storage: Nfts Account (r:0 w:1)
	/// Proof: Nfts Account (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_upgrade_item(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `6036`
		// Minimum execution time: 112_000_000 picoseconds.
		Weight::from_parts(114_422_183, 6036)
			// Standard Error: 9_135
			.saturating_add(Weight::from_parts(6_154, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: Game LevelOf (r:1 w:0)
	/// Proof: Game LevelOf (max_values: None, max_size: Some(44), added: 2519, mode: MaxEncodedLen)
	/// Storage: Game OriginItemOf (r:1 w:0)
	/// Proof: Game OriginItemOf (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Game UpgradeConfigOf (r:1 w:0)
	/// Proof: Game UpgradeConfigOf (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn upgrade_item(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `720`
		//  Estimated: `6108`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(47_178_081, 6108)
			// Standard Error: 8_442
			.saturating_add(Weight::from_parts(66_796, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:1 w:1)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_price(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `695`
		//  Estimated: `3606`
		// Minimum execution time: 64_000_000 picoseconds.
		Weight::from_parts(66_164_571, 3606)
			// Standard Error: 10_432
			.saturating_add(Weight::from_parts(4_298, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:0)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:1 w:1)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn buy_item(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `874`
		//  Estimated: `3667`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(56_220_034, 3667)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_bundle(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `6108`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(71_797_206, 6108)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:2 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn buy_bundle(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1012`
		//  Estimated: `6108`
		// Minimum execution time: 90_000_000 picoseconds.
		Weight::from_parts(92_256_097, 6108)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_wishlist(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `179`
		//  Estimated: `3606`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(50_079_928, 3606)
			// Standard Error: 6_021
			.saturating_add(Weight::from_parts(19_484, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:2 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_wishlist(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `883`
		//  Estimated: `6108`
		// Minimum execution time: 102_000_000 picoseconds.
		Weight::from_parts(104_484_917, 6108)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game GameRoleOf (r:1 w:0)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game CollectionsOf (r:1 w:1)
	/// Proof: Game CollectionsOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Game GamesOf (r:0 w:1)
	/// Proof: Game GamesOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn remove_collection(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460`
		//  Estimated: `3534`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(23_802_546, 3534)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_swap(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `6108`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(70_806_883, 6108)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:4 w:4)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_swap(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `726`
		//  Estimated: `11226`
		// Minimum execution time: 109_000_000 picoseconds.
		Weight::from_parts(111_848_788, 11226)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game AuctionConfigOf (r:0 w:1)
	/// Proof: Game AuctionConfigOf (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_auction(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `6108`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(70_436_441, 6108)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Game AuctionConfigOf (r:1 w:0)
	/// Proof: Game AuctionConfigOf (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
	/// Storage: Game HighestBidOf (r:1 w:1)
	/// Proof: Game HighestBidOf (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn bid_auction(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `445`
		//  Estimated: `3593`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_411_522, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Game AuctionConfigOf (r:1 w:1)
	/// Proof: Game AuctionConfigOf (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
	/// Storage: Game HighestBidOf (r:1 w:1)
	/// Proof: Game HighestBidOf (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_auction(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `712`
		//  Estimated: `6108`
		// Minimum execution time: 97_000_000 picoseconds.
		Weight::from_parts(100_718_528, 6108)
			// Standard Error: 10_121
			.saturating_add(Weight::from_parts(32_626, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_buy(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3606`
		// Minimum execution time: 49_000_000 picoseconds.
		Weight::from_parts(51_045_928, 3606)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:0)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_set_buy(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `871`
		//  Estimated: `3667`
		// Minimum execution time: 67_000_000 picoseconds.
		Weight::from_parts(69_297_945, 3667)
			// Standard Error: 7_480
			.saturating_add(Weight::from_parts(22_135, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Nfts NextCollectionId (r:1 w:1)
	/// Proof: Nfts NextCollectionId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:0 w:1)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:0 w:1)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionAccount (r:0 w:1)
	/// Proof: Nfts CollectionAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_collection(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3593`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(49_336_536, 3593)
			// Standard Error: 8_639
			.saturating_add(Weight::from_parts(27_314, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game AddingAcceptance (r:0 w:1)
	/// Proof: Game AddingAcceptance (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_accept_adding(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `401`
		//  Estimated: `3593`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_747_263, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Game GameRoleOf (r:1 w:0)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game AddingAcceptance (r:1 w:0)
	/// Proof: Game AddingAcceptance (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	/// Storage: Game CollectionsOf (r:1 w:1)
	/// Proof: Game CollectionsOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Game GamesOf (r:1 w:1)
	/// Proof: Game GamesOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn add_game_collection(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `212`
		//  Estimated: `3534`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_869_768, 3534)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:0)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:1 w:1)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn add_retail_supply(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `874`
		//  Estimated: `3667`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(45_867_865, 3667)
			// Standard Error: 5_346
			.saturating_add(Weight::from_parts(25_250, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn cancel_trade(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `611`
		//  Estimated: `6108`
		// Minimum execution time: 79_000_000 picoseconds.
		Weight::from_parts(81_232_465, 6108)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: Game NextPoolId (r:1 w:1)
	/// Proof: Game NextPoolId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game PoolOf (r:1 w:1)
	/// Proof: Game PoolOf (max_values: None, max_size: Some(124), added: 2599, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:3 w:3)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:3 w:3)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game LootTableOf (r:0 w:1)
	/// Proof: Game LootTableOf (max_values: None, max_size: Some(147), added: 2622, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_dynamic_pool(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `8667`
		// Minimum execution time: 84_000_000 picoseconds.
		Weight::from_parts(86_249_337, 8667)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	/// Storage: Game NextPoolId (r:1 w:1)
	/// Proof: Game NextPoolId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game SupplyOf (r:3 w:0)
	/// Proof: Game SupplyOf (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game LootTableOf (r:0 w:1)
	/// Proof: Game LootTableOf (max_values: None, max_size: Some(147), added: 2622, mode: MaxEncodedLen)
	/// Storage: Game PoolOf (r:0 w:1)
	/// Proof: Game PoolOf (max_values: None, max_size: Some(124), added: 2599, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_stable_pool(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `8550`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(53_003_664, 8550)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Game PoolOf (r:1 w:0)
	/// Proof: Game PoolOf (max_values: None, max_size: Some(124), added: 2599, mode: MaxEncodedLen)
	/// Storage: Game LootTableOf (r:1 w:0)
	/// Proof: Game LootTableOf (max_values: None, max_size: Some(147), added: 2622, mode: MaxEncodedLen)
	/// Storage: Game RandomSeed (r:1 w:0)
	/// Proof: Game RandomSeed (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn mint(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286`
		//  Estimated: `4079`
		// Minimum execution time: 115_000_000 picoseconds.
		Weight::from_parts(117_724_001, 4079)
			// Standard Error: 10_077
			.saturating_add(Weight::from_parts(84_955, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Game NextGameId (r:1 w:1)
	/// Proof: Game NextGameId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game GameAccount (r:0 w:1)
	/// Proof: Game GameAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Game Game (r:0 w:1)
	/// Proof: Game Game (max_values: None, max_size: Some(96), added: 2571, mode: MaxEncodedLen)
	/// Storage: Game GameRoleOf (r:0 w:1)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_game(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3593`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(37_361_427, 3593)
			// Standard Error: 7_566
			.saturating_add(Weight::from_parts(10_746, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Game GameRoleOf (r:1 w:0)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game Game (r:1 w:0)
	/// Proof: Game Game (max_values: None, max_size: Some(96), added: 2571, mode: MaxEncodedLen)
	/// Storage: Nfts NextCollectionId (r:1 w:1)
	/// Proof: Nfts NextCollectionId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game CollectionsOf (r:1 w:1)
	/// Proof: Game CollectionsOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Game GamesOf (r:1 w:1)
	/// Proof: Game GamesOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:0 w:1)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:0 w:1)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionAccount (r:0 w:1)
	/// Proof: Nfts CollectionAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_game_collection(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `388`
		//  Estimated: `3593`
		// Minimum execution time: 59_000_000 picoseconds.
		Weight::from_parts(61_561_967, 3593)
			// Standard Error: 7_486
			.saturating_add(Weight::from_parts(14_608, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts Item (r:1 w:1)
	/// Proof: Nfts Item (max_values: None, max_size: Some(491), added: 2966, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:1)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game SupplyOf (r:0 w:1)
	/// Proof: Game SupplyOf (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
	/// Storage: Nfts Account (r:0 w:1)
	/// Proof: Nfts Account (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_item(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `3956`
		// Minimum execution time: 72_000_000 picoseconds.
		Weight::from_parts(74_392_577, 3956)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game SupplyOf (r:1 w:1)
	/// Proof: Game SupplyOf (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn add_supply(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `513`
		//  Estimated: `3549`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_340_427, 3549)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn burn(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3549`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_358_161, 3549)
			// Standard Error: 7_583
			.saturating_add(Weight::from_parts(13_681, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn transfer(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3549`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_023_896, 3549)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:2 w:1)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemMetadataOf (r:1 w:1)
	/// Proof: Nfts ItemMetadataOf (max_values: None, max_size: Some(140), added: 2615, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game UpgradeConfigOf (r:1 w:1)
	/// Proof: Game UpgradeConfigOf (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// Storage: Nfts Item (r:1 w:1)
	/// Proof: Nfts Item (max_values: None, max_size: Some(491), added: 2966, mode: MaxEncodedLen)
	/// Storage: Game OriginItemOf (r:0 w:1)
	/// Proof: Game OriginItemOf (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Game LevelOf (r:0 w:1)
	/// Proof: Game LevelOf (max_values: None, max_size: Some(44), added: 2519, mode: MaxEncodedLen)
	/// Storage: Nfts Account (r:0 w:1)
	/// Proof: Nfts Account (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_upgrade_item(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `6036`
		// Minimum execution time: 112_000_000 picoseconds.
		Weight::from_parts(114_422_183, 6036)
			// Standard Error: 9_135
			.saturating_add(Weight::from_parts(6_154, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: Game LevelOf (r:1 w:0)
	/// Proof: Game LevelOf (max_values: None, max_size: Some(44), added: 2519, mode: MaxEncodedLen)
	/// Storage: Game OriginItemOf (r:1 w:0)
	/// Proof: Game OriginItemOf (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Game UpgradeConfigOf (r:1 w:0)
	/// Proof: Game UpgradeConfigOf (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn upgrade_item(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `720`
		//  Estimated: `6108`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(47_178_081, 6108)
			// Standard Error: 8_442
			.saturating_add(Weight::from_parts(66_796, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:1 w:1)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_price(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `695`
		//  Estimated: `3606`
		// Minimum execution time: 64_000_000 picoseconds.
		Weight::from_parts(66_164_571, 3606)
			// Standard Error: 10_432
			.saturating_add(Weight::from_parts(4_298, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:0)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:1 w:1)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn buy_item(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `874`
		//  Estimated: `3667`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(56_220_034, 3667)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_bundle(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `6108`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(71_797_206, 6108)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:2 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn buy_bundle(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1012`
		//  Estimated: `6108`
		// Minimum execution time: 90_000_000 picoseconds.
		Weight::from_parts(92_256_097, 6108)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_wishlist(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `179`
		//  Estimated: `3606`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(50_079_928, 3606)
			// Standard Error: 6_021
			.saturating_add(Weight::from_parts(19_484, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:2 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_wishlist(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `883`
		//  Estimated: `6108`
		// Minimum execution time: 102_000_000 picoseconds.
		Weight::from_parts(104_484_917, 6108)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game GameRoleOf (r:1 w:0)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game CollectionsOf (r:1 w:1)
	/// Proof: Game CollectionsOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Game GamesOf (r:0 w:1)
	/// Proof: Game GamesOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn remove_collection(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460`
		//  Estimated: `3534`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(23_802_546, 3534)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_swap(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `6108`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(70_806_883, 6108)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:4 w:4)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_swap(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `726`
		//  Estimated: `11226`
		// Minimum execution time: 109_000_000 picoseconds.
		Weight::from_parts(111_848_788, 11226)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game AuctionConfigOf (r:0 w:1)
	/// Proof: Game AuctionConfigOf (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_auction(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `6108`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(70_436_441, 6108)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Game AuctionConfigOf (r:1 w:0)
	/// Proof: Game AuctionConfigOf (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
	/// Storage: Game HighestBidOf (r:1 w:1)
	/// Proof: Game HighestBidOf (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn bid_auction(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `445`
		//  Estimated: `3593`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_411_522, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Game AuctionConfigOf (r:1 w:1)
	/// Proof: Game AuctionConfigOf (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
	/// Storage: Game HighestBidOf (r:1 w:1)
	/// Proof: Game HighestBidOf (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_auction(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `712`
		//  Estimated: `6108`
		// Minimum execution time: 97_000_000 picoseconds.
		Weight::from_parts(100_718_528, 6108)
			// Standard Error: 10_121
			.saturating_add(Weight::from_parts(32_626, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Game NextTradeId (r:1 w:1)
	/// Proof: Game NextTradeId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game TradeConfigOf (r:0 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_buy(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3606`
		// Minimum execution time: 49_000_000 picoseconds.
		Weight::from_parts(51_045_928, 3606)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:0)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn claim_set_buy(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `871`
		//  Estimated: `3667`
		// Minimum execution time: 67_000_000 picoseconds.
		Weight::from_parts(69_297_945, 3667)
			// Standard Error: 7_480
			.saturating_add(Weight::from_parts(22_135, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Nfts NextCollectionId (r:1 w:1)
	/// Proof: Nfts NextCollectionId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:1)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:0 w:1)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:0 w:1)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionAccount (r:0 w:1)
	/// Proof: Nfts CollectionAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_collection(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3593`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(49_336_536, 3593)
			// Standard Error: 8_639
			.saturating_add(Weight::from_parts(27_314, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionRoleOf (r:1 w:0)
	/// Proof: Nfts CollectionRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game AddingAcceptance (r:0 w:1)
	/// Proof: Game AddingAcceptance (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn set_accept_adding(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `401`
		//  Estimated: `3593`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_747_263, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Game GameRoleOf (r:1 w:0)
	/// Proof: Game GameRoleOf (max_values: None, max_size: Some(69), added: 2544, mode: MaxEncodedLen)
	/// Storage: Game AddingAcceptance (r:1 w:0)
	/// Proof: Game AddingAcceptance (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	/// Storage: Game CollectionsOf (r:1 w:1)
	/// Proof: Game CollectionsOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Game GamesOf (r:1 w:1)
	/// Proof: Game GamesOf (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn add_game_collection(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `212`
		//  Estimated: `3534`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_869_768, 3534)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:0)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Nfts CollectionConfigOf (r:1 w:0)
	/// Proof: Nfts CollectionConfigOf (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: Nfts ItemConfigOf (r:1 w:0)
	/// Proof: Nfts ItemConfigOf (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:1 w:1)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn add_retail_supply(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `874`
		//  Estimated: `3667`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(45_867_865, 3667)
			// Standard Error: 5_346
			.saturating_add(Weight::from_parts(25_250, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Game TradeConfigOf (r:1 w:1)
	/// Proof: Game TradeConfigOf (max_values: None, max_size: Some(202), added: 2677, mode: MaxEncodedLen)
	/// Storage: Game BundleOf (r:1 w:1)
	/// Proof: Game BundleOf (max_values: None, max_size: Some(141), added: 2616, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:2 w:2)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:2 w:2)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn cancel_trade(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `611`
		//  Estimated: `6108`
		// Minimum execution time: 79_000_000 picoseconds.
		Weight::from_parts(81_232_465, 6108)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: Game NextPoolId (r:1 w:1)
	/// Proof: Game NextPoolId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Game PoolOf (r:1 w:1)
	/// Proof: Game PoolOf (max_values: None, max_size: Some(124), added: 2599, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:3 w:3)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game ReservedBalanceOf (r:3 w:3)
	/// Proof: Game ReservedBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game LootTableOf (r:0 w:1)
	/// Proof: Game LootTableOf (max_values: None, max_size: Some(147), added: 2622, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_dynamic_pool(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `8667`
		// Minimum execution time: 84_000_000 picoseconds.
		Weight::from_parts(86_249_337, 8667)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	/// Storage: Game NextPoolId (r:1 w:1)
	/// Proof: Game NextPoolId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Nfts Collection (r:1 w:0)
	/// Proof: Nfts Collection (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Game SupplyOf (r:3 w:0)
	/// Proof: Game SupplyOf (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Game LootTableOf (r:0 w:1)
	/// Proof: Game LootTableOf (max_values: None, max_size: Some(147), added: 2622, mode: MaxEncodedLen)
	/// Storage: Game PoolOf (r:0 w:1)
	/// Proof: Game PoolOf (max_values: None, max_size: Some(124), added: 2599, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn create_stable_pool(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `8550`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(53_003_664, 8550)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Game PoolOf (r:1 w:0)
	/// Proof: Game PoolOf (max_values: None, max_size: Some(124), added: 2599, mode: MaxEncodedLen)
	/// Storage: Game LootTableOf (r:1 w:0)
	/// Proof: Game LootTableOf (max_values: None, max_size: Some(147), added: 2622, mode: MaxEncodedLen)
	/// Storage: Game RandomSeed (r:1 w:0)
	/// Proof: Game RandomSeed (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Game ItemBalanceOf (r:1 w:1)
	/// Proof: Game ItemBalanceOf (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 10]`.
	fn mint(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286`
		//  Estimated: `4079`
		// Minimum execution time: 115_000_000 picoseconds.
		Weight::from_parts(117_724_001, 4079)
			// Standard Error: 10_077
			.saturating_add(Weight::from_parts(84_955, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
